"""Generate high-precision reference values for the C++ test suite.

Everything in the test suite is checked against something. For the closed-form
layer, "something" is a 50-decimal-digit mpmath evaluation of the same formula,
not a textbook table rounded to four places -- four places cannot distinguish a
correct implementation from one that is wrong in the 8th digit, which is exactly
the failure mode this project exists to rule out.

Writes cpp/tests/reference_values.hpp. Regenerate with:

    python scripts/gen_reference.py
"""

from __future__ import annotations

import pathlib

import mpmath as mp

mp.mp.dps = 60

HERE = pathlib.Path(__file__).resolve().parent
OUT = HERE.parent / "cpp" / "tests" / "reference_values.hpp"


def norm_cdf(x):
    return mp.erfc(-x / mp.sqrt(2)) / 2


def bs_call(S, K, T, r, q, sig):
    S, K, T, r, q, sig = map(mp.mpf, (S, K, T, r, q, sig))
    srt = sig * mp.sqrt(T)
    d1 = (mp.log(S / K) + (r - q + sig**2 / 2) * T) / srt
    d2 = d1 - srt
    return S * mp.e ** (-q * T) * norm_cdf(d1) - K * mp.e ** (-r * T) * norm_cdf(d2)


def bs_put(S, K, T, r, q, sig):
    S, K, T, r, q, sig = map(mp.mpf, (S, K, T, r, q, sig))
    srt = sig * mp.sqrt(T)
    d1 = (mp.log(S / K) + (r - q + sig**2 / 2) * T) / srt
    d2 = d1 - srt
    return K * mp.e ** (-r * T) * norm_cdf(-d2) - S * mp.e ** (-q * T) * norm_cdf(-d1)


def normalised_black(x, s):
    """b(x,s) = e^{x/2} N(x/s + s/2) - e^{-x/2} N(x/s - s/2)."""
    x, s = mp.mpf(x), mp.mpf(s)
    return mp.e ** (x / 2) * norm_cdf(x / s + s / 2) - mp.e ** (-x / 2) * norm_cdf(x / s - s / 2)


def lit(v) -> str:
    return mp.nstr(mp.mpf(v), 20, strip_zeros=False)


# (S, K, T, r, q, sigma) covering ATM, both wings, short and long dated,
# negative rates, and a dividend-bearing underlying.
BS_CASES = [
    (100.0, 100.0, 1.0, 0.05, 0.00, 0.20),
    (100.0, 100.0, 1.0, 0.00, 0.00, 0.20),
    (100.0, 130.0, 0.5, 0.03, 0.01, 0.35),
    (100.0, 70.0, 0.5, 0.03, 0.01, 0.35),
    (100.0, 100.0, 1.0 / 365.0, 0.04, 0.00, 0.60),
    (100.0, 100.0, 5.0, 0.02, 0.03, 0.25),
    (4200.0, 4500.0, 0.25, 0.045, 0.015, 0.18),
    (100.0, 100.0, 2.0, -0.005, 0.00, 0.15),
    (50.0, 200.0, 3.0, 0.03, 0.00, 0.40),
    (200.0, 50.0, 3.0, 0.03, 0.00, 0.40),
]

# (x, s) for the normalised Black function, pushed deliberately into the wings
# where the naive difference-of-CDFs form loses all significant digits.
NB_CASES = [
    (0.0, 0.2),
    (0.0, 0.01),
    (0.0, 2.0),
    (-0.5, 0.3),
    (0.5, 0.3),
    (-2.0, 0.25),
    (2.0, 0.25),
    (-4.0, 0.4),
    (-1.0, 0.05),
    (-3.0, 0.1),
    (-0.001, 0.5),
    (-8.0, 0.6),
]

NORM_CDF_CASES = [0.0, 0.5, -0.5, 1.0, -1.0, 3.0, -3.0, 7.0, -7.0, 10.0, -10.0, 20.0, -20.0, 36.0, -36.0]


def main() -> None:
    lines = [
        "// GENERATED by scripts/gen_reference.py -- do not edit by hand.",
        "//",
        "// Reference values evaluated at 60 decimal digits with mpmath and rounded to",
        "// the nearest double. A test that passes against these is correct to the last",
        "// bit the type can carry, which is the only tolerance worth asserting for a",
        "// closed-form pricer.",
        "#pragma once",
        "",
        "namespace vsetest {",
        "",
        "struct BSRef { double S, K, T, r, q, sigma, call, put; };",
        "",
        "inline constexpr BSRef kBSReference[] = {",
    ]
    for S, K, T, r, q, sig in BS_CASES:
        c = bs_call(S, K, T, r, q, sig)
        p = bs_put(S, K, T, r, q, sig)
        lines.append(
            f"    {{{lit(S)}, {lit(K)}, {lit(T)}, {lit(r)}, {lit(q)}, {lit(sig)},"
            f"\n     {lit(c)}, {lit(p)}}},"
        )
    lines += ["};", "", "struct NBRef { double x, s, b; };", "",
              "inline constexpr NBRef kNormalisedBlackReference[] = {"]
    for x, s in NB_CASES:
        lines.append(f"    {{{lit(x)}, {lit(s)}, {lit(normalised_black(x, s))}}},")
    lines += ["};", "", "struct CdfRef { double x, cdf; };", "",
              "inline constexpr CdfRef kNormCdfReference[] = {"]
    for x in NORM_CDF_CASES:
        lines.append(f"    {{{lit(x)}, {lit(norm_cdf(mp.mpf(x)))}}},")
    lines += ["};", "", "}  // namespace vsetest", ""]

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} ({len(BS_CASES)} BS + {len(NB_CASES)} normalised-Black "
          f"+ {len(NORM_CDF_CASES)} CDF references)")


if __name__ == "__main__":
    main()
